# Generated by Django 5.1.2 on 2025-04-23 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandSocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('uid', models.CharField(max_length=255)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_expires', models.DateTimeField(blank=True, null=True)),
                ('extra_data', models.JSONField(default=dict)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='core.brand')),
            ],
            options={
                'verbose_name': 'Brand Social Account',
                'verbose_name_plural': 'Brand Social Accounts',
                'unique_together': {('brand', 'provider', 'uid')},
            },
        ),
    ]
